/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.Conexion;
import controlador.ServicioController;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Servicio;

/**
 *
 * @author jhonb
 */
public class PanelServicios extends javax.swing.JPanel {

    /**
     * Creates new form PanelServicios
     */
    Servicio servicio = new Servicio();
    ServicioController servicioControl = new ServicioController();

    public PanelServicios() {
        initComponents();
        lbPrecioServicio.setText("");
        DefaultComboBoxModel mostrarNombre = new DefaultComboBoxModel(servicio.nombreServicio());
        cbServicios.setModel(mostrarNombre);
        servicioControl.cosultaMotoServicio(cbElejirMoto);

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbServicios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbElejirMoto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lbPrecioServicio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Servicios"));
        setToolTipText("");
        setName(""); // NOI18N

        jLabel1.setText("Nombre del servicios");

        cbServicios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbServiciosItemStateChanged(evt);
            }
        });
        cbServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbServiciosActionPerformed(evt);
            }
        });

        jLabel2.setText("Elija la moto");

        jLabel3.setText("VALOR DEL SERVICIO");

        lbPrecioServicio.setText("jLabel4");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jLabel5.setText("Descripcion del servicio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbElejirMoto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbServicios, javax.swing.GroupLayout.Alignment.LEADING, 0, 171, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lbPrecioServicio)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbElejirMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lbPrecioServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServiciosActionPerformed
        // TODO add your handling code here:
//        mostrarPrecio();
//        servicioControl.cosultaPrecioServicio(lbPrecioServicio);
    }//GEN-LAST:event_cbServiciosActionPerformed

    private void cbServiciosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbServiciosItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Servicio servicioCon = (Servicio) cbServicios.getSelectedItem();
            try {
                PreparedStatement ps;
                ResultSet rs;
                Conexion conetar = new Conexion();
                Connection con = conetar.conexion();
                String sql = "select precio from servicios where id_srevicio=" + servicioCon.getIdServicio();
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();
                while (rs.next()) {
                    lbPrecioServicio.setText(rs.getString("precio"));

                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
            if (evt.getStateChange() == ItemEvent.SELECTED){
                try {
                PreparedStatement ps;
                ResultSet rs;
                Conexion conetar = new Conexion();
                Connection con = conetar.conexion();
                String sql = "select descripcion from servicios where id_srevicio=" + servicioCon.getIdServicio();
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();
                while (rs.next()) {
                    txtArea.setText(rs.getString("descripcion"));

                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
            }
        }
    }//GEN-LAST:event_cbServiciosItemStateChanged

//    public void mostrarPrecio(){
//        lbPrecioServicio.setText(Integer.toString(cbServicios.getSelectedIndex()));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbElejirMoto;
    private javax.swing.JComboBox<String> cbServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbPrecioServicio;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
