/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author jhonb
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmIncio = new javax.swing.JMenu();
        itemCerrarSecion = new javax.swing.JMenuItem();
        jmMoto = new javax.swing.JMenu();
        itAlladirMoto = new javax.swing.JMenuItem();
        jmServicios = new javax.swing.JMenu();
        jmRepuesto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        jmIncio.setText("Inicio");

        itemCerrarSecion.setText("Cerrar Secion");
        jmIncio.add(itemCerrarSecion);

        jMenuBar1.add(jmIncio);

        jmMoto.setText("Moto");
        jmMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMotoActionPerformed(evt);
            }
        });

        itAlladirMoto.setText("Alladir moto");
        itAlladirMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itAlladirMotoActionPerformed(evt);
            }
        });
        jmMoto.add(itAlladirMoto);

        jMenuBar1.add(jmMoto);

        jmServicios.setText("Servicios");
        jMenuBar1.add(jmServicios);

        jmRepuesto.setText("Repusto");
        jMenuBar1.add(jmRepuesto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMotoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jmMotoActionPerformed

    private void itAlladirMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAlladirMotoActionPerformed
        // TODO add your handling code here:
         VistaCrearMoto vistaMoto = new VistaCrearMoto();
        escritorio.add(vistaMoto);
        vistaMoto.setVisible(true);
    }//GEN-LAST:event_itAlladirMotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itAlladirMoto;
    private javax.swing.JMenuItem itemCerrarSecion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmIncio;
    private javax.swing.JMenu jmMoto;
    private javax.swing.JMenu jmRepuesto;
    private javax.swing.JMenu jmServicios;
    // End of variables declaration//GEN-END:variables
}
